version: "3.9"
services:
  # База данных
  database:
    image: "postgres:16"
    container_name: "wallet-database"
    ports:
      - "1313:5432"
    environment:
      POSTGRES_USER: "walletadmin"
      POSTGRES_PASSWORD: "walletadmin"
      POSTGRES_DB: "wallet"
    volumes:
      - "database:/var/lib/postgresql/data"
    restart: "always"

volumes:
  database:
    name: "wallet-database-data"