#
# Copyright © 2023 Алексей Каленчуков
# GitHub: https://github.com/kalenchukov
# E-mail: mailto:aleksey.kalenchukov@yandex.ru
#

context: production

# Database
database:
  # URL базы данных.
  url: jdbc:postgresql://localhost:1313/wallet
  # Пользователь.
  username: walletadmin
  # Пароль.
  password: walletadmin

# Liquibase
liquibase:
  # Путь к файлам миграции.
  changeLogFile: db/changelog/changelog.xml
  # Схема для служебных таблиц.
  schema: migration
  # Схема для таблиц приложения.
  schemaApp: wallet
  # Необходимые миграции.
  contexts: production

# AccessToken
accessToken:
  # Сервер авторизации выдавший токен доступа.
  server: WalletAuth
  # Время жизни токена доступа в секундах.
  ttl: 1800
  # Строка для формирования токенов доступа.
  secret: WalletSecretCode123