#
# Copyright © 2023 Алексей Каленчуков
# GitHub: https://github.com/kalenchukov
# E-mail: mailto:aleksey.kalenchukov@yandex.ru
#

# Сервер
server:
  port: 1111

spring:
  # База данных
  datasource:
    url: jdbc:postgresql://localhost:1313/wallet
    username: walletadmin
    password: walletadmin
  # SQL
  sql:
    init:
      schema-locations: classpath:/preliquibase/default.sql
  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    default-schema: wallet
    liquibase-schema: migration
    contexts: production

# AccessToken
access-token:
  server: WalletAuth
  ttl: 1800
  secret: WalletSecretCode123